const colors = {
  BACKGROUND: 'url(/images/background-macos.jpg)',
  TERMINAL_BACKGROUND: '#1F1C25',
  TERMINAL_BACKGROUND_HEADER: 'transparent',
  TERMINAL_CLOSE: '#F25F52',
  TERMINAL_MAXIMIZE: '#F8B543',
  TERMINAL_MINIMIZE: '#4CBB4A',
  TERMINAL_CHEVRON_INACTIVE: '#CC3737',
  TERMINAL_CHEVRON_ACTIVE: '#4CBB4A',
  TERMINAL_LABEL_TREE_COLOR: '#B24782',
  TERMINAL_LABEL_DEFAULT_COLOR: '#6D6D6D',
  TERMINAL_LABEL_ACTIVE_COLOR: '#D7D7D7',
  TERMINAL_LABEL_TITLE_COLOR: '#CECECE',
  TERMINAL_CURSOR_COLOR: '#BDBDBD',
} as const

export default colors
